# Rutas de productos
paths:
  /api/products:
    get:
      summary: Endpoint para obtener todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Se obtuvieron correctamente los productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: object
                    properties:
                      docs:
                        type: array
                        items:
                          $ref: "#components/schemas/Products"
                      totalDocs:
                        type: number
                        example: 1
                      limit:
                        type: number
                        example: 10
                      totalPages:
                        type: number
                        example: 1
                      page:
                        type: number
                        example: 1
                      pagingCounter:
                        type: number
                        example: 1
                      hasPrevPage:
                        type: boolean
                        example: false
                      hasNextPage:
                        type: boolean
                        example: false
                      prevPage:
                        type: null
                        example: null
                      nextPage:
                        type: null
                        example: null
    post:
      summary: Endpoint para agregar un producto
      tags:
        - Productos
      responses:
        "200":
          description: Se agreg贸 correctamente el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: producto agregado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/BodyProduct"
  /api/products/{pid}:
    parameters:
      - name: uid
        in: path
        required: true
        description: id del producto
        schema:
          type: string
    get:
      summary: Endpoint para obtener un producto
      tags:
        - Productos
      responses:
        "200":
          description: Se obtuvo correctamente el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: object
                    $ref: "#components/schemas/Products"
    put:
      summary: Endpoint para actualizar un producto
      tags:
        - Productos
      responses:
        "200":
          description: Se actualiz贸 correctamente el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: producto actualizado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/BodyProduct"
    delete:
      summary: Endpoint para eliminar un producto
      tags:
        - Productos
      responses:
        "200":
          description: Se elimin贸 correctamente el producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: producto eliminado

components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: objectId
          description: id del producto generado por mongoDB
        title:
          type: string
          description: id del producto generado por mongoDB
        description:
          type: string
          description: id del producto generado por mongoDB
        price:
          type: number
          description: id del producto generado por mongoDB
        thumbnails:
          type: string
          description: id del producto generado por mongoDB
        code:
          type: string
          description: id del producto generado por mongoDB
        stock:
          type: number
          description: id del producto generado por mongoDB
        status:
          type: boolean
          description: id del producto generado por mongoDB
        category:
          type: string
          description: id del producto generado por mongoDB
        owner:
          type: objectId
          description: id del creador del producto
        __v:
          type: number
          description: version del producto
      example:
        _id: 65715d44fc6e3e93e42353cb
        title: musculosa
        description: negra
        price: 24000
        thumbnails: sin imagen
        code: 342113
        stock: 23
        status: true
        category: remeras
        owner: 65714f651e407ced0048ba99
        __v: 4
  requestBodies:
    BodyProduct:
      properties:
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripci贸n del producto
        price:
          type: number
          description: precio del producto
        thumbnails:
          type: string
          description: imagenes del producto
        code:
          type: string
          description: codigo del producto
        stock:
          type: number
          description: cantidad disponible del producto
        status:
          type: boolean
          description: estado del producto
        category:
          type: string
          description: categoria del producto
      example:
        title: remera
        description: naranja
        price: 14000
        thumbnails: sin imagen
        code: 39949113
        stock: 12
        status: true
        category: remeras